### ISSUE TITLE
Cannot find module '@remix-run/react/routeData' or its corresponding type declarations.

### ISSUE THREAD

**Issue by felangel** [sergiodxa/remix-utils#118]
### Describe the bug

When using `"@remix-run/react": "1.7.5"` with `DynamicLinks` from `"remix-utils": "^4.2.1"`, I see the following error after running a build:

```sh
npm run build
Done in 320ms.
Building Remix app in production mode...
Built in 258ms
node_modules/remix-utils/build/react/handle-conventions.d.ts:1:32 - error TS2307: Cannot find module '@remix-run/react/routeData' or its corresponding type declarations.

1 import type { RouteData } from "@remix-run/react/routeData";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```
### GitHub Repo

https://github.com/brick-hub/brickhub.dev/actions/runs/3562380363

### Steps to Reproduce the Bug or Issue

1. Run a remix.run app using remix >=1.7.5 and remix-utils 4.2.1 with `DynamicLinks`
2. Do a build (`npm run build`)

### Expected behavior

I expect the build to complete successfully with no errors.

### Platform

- OS: macOS
- Browser: Chrome

**Comment by corygibbons** [comment]
I'm experiencing the same issue as well.

**Comment by felangel** [comment]
fwiw it looks like the `RouteData` import needs to be updated:

```diff
- import type { RouteData } from "@remix-run/react/routeData";
+ import type { RouteData } from "@remix-run/react/dist/routeData";
```

**Comment by colinweight** [comment]
Also getting this error running type checks. We're using yarn workspaces, and I've used `yarn patch` to add a `@ts-ignore` above the import line in `build/react/handle-conventions.d.ts` as a temporary fix
