### ISSUE TITLE
`cors` function inside `entry.server.tsx` doesn't do anything

### ISSUE THREAD

**Issue by v-zdorovcev** [sergiodxa/remix-utils#136]
### Describe the bug

As indicated in the documentation, I have made a global configuration for all loaders
```ts
export const handleDataRequest: HandleDataRequestFunction = async (
  response,
  { request }
) => {
  return await cors(request, response);
};
```
But the response will not get changed in any way.
![image](https://user-images.githubusercontent.com/72477415/208632512-1d3cec91-b680-4a8d-ac44-fbce8a86498b.png)

### Your Example Website or App

https://stackblitz.com/edit/node-9lk4se?file=app/entry.server.tsx

### Steps to Reproduce the Bug or Issue

1. go to devtools
2. open network section
3. select response with `_data` query param

### Expected behavior

CORS headers with default values will be setup on each loader with the `_data` param

### Platform

- OS: Ubuntu 22.04.1 LTS
- Browser: Chrome
- Version: 108.0.5359

**Comment by gdonoso94** [comment]
It doesn't do anything either in a Loader, the response doesn't have any additional headers

**Comment by arnaudambro** [comment]
wow I didn't spot that part

```
		cors(
						request,
						new Response(body, {
							headers: responseHeaders,
							status: didError ? 500 : responseStatusCode,
						}),
					).then((response) => {
						resolve(response);
					});
```

can it be highlighted somehow ?
