### ISSUE TITLE
TypedSessionStorage break api

### ISSUE THREAD

**Issue by tomer-rmor** [sergiodxa/remix-utils#141]
### Describe the bug

the api of SessionStorage.getSession is the following:

![image](https://user-images.githubusercontent.com/119947737/210544506-76102867-7df2-420b-af76-9d77d63a4fc6.png)

but TypedSessionStorage doesn't behave the same, it throw exception if there is no session instead of creating one

### Your Example Website or App

NA

### Steps to Reproduce the Bug or Issue

this line throw exception if there is no session
![image](https://user-images.githubusercontent.com/119947737/210546039-bdda8d90-eee3-4b24-990f-7dcba75db6be.png)

### Expected behavior

should create a session if not exist if the library suppose to be drop in replacement

### Platform

NA

**Comment by sergiodxa** [comment]
Could you provide a reproduction repo?

---

When you call `typedSessionStorage.getSession` it first calls the original `sessionStorage.getSession` method:

https://github.com/sergiodxa/remix-utils/blob/8b3898dab8121b9bea2782750fe0798777b61b29/src/server/typed-session.ts#L85-L88

This should be creating your session first, then the returned Session object is converted to a TypedSession object.

There's also a test (actually many) where I call `typedSessionStorage.getSession` without any argument and it's creating the session:

https://github.com/sergiodxa/remix-utils/blob/8b3898dab8121b9bea2782750fe0798777b61b29/test/server/typed-session.test.ts#L83-L95

Additionally, I have been using TypedSessionStorage on my own personal website together with Remix Auth as a drop-in replacement of SessionStorage and it works without throwing.

https://github.com/sergiodxa/sergiodxa.com/blob/fcdb80b475f1f7935d5d99994e4d71781b402067/services/auth.ts#L53-L56

**Comment by tomer-rmor** [comment]
tried to create reproduction and you are right it probably my mistake, sorry
