### ISSUE TITLE
eventSource is not working on Grunge Stack

### ISSUE THREAD

**Issue by cjoecker** [sergiodxa/remix-utils#176]
### Describe the bug

I followed the example in the docs for `eventSource` inside of the Remix Grunge Stack. Then, I'm becoming a 500 error on http://localhost:3000/time.

Here you have a repository where you can replicate the error:
https://github.com/cjoecker/remix-event-source

### Your Example Website or App

https://github.com/cjoecker/remix-event-source

### Steps to Reproduce the Bug or Issue

1. Clone this repo: `https://github.com/cjoecker/remix-event-source`
2. Run `npm i` and `npx remix init`
3. Start the app with `npm run dev`
4. Go to `http://localhost:3000/time`
5. Open the console and see the error

### Expected behavior

No 500 error should be shown

### Platform

- OS: macOS
- Browser: Chrome
- Remix Grunge Stack

**Comment by sergiodxa** [comment]
Grunge Stack deploys to AWS Lambda if I remember correctly, on AWS Lambda you can't use HTTP streaming which means you can't use Server Sent Events, so `eventSource` will not work there.
