### ISSUE TITLE
Support `Graph` type for `StructuredDataFunction`

### ISSUE THREAD

**Issue by zipme** [sergiodxa/remix-utils#182]
### Describe the bug

It should be possible to use `@graph` for structured data:
```ts
const structuredData: StructuredDataFunction<
  SerializeFrom<typeof loader>,
  Graph
> = (data) => {
  return {
    "@context": "https://schema.org",
    "@graph": [{
        "@type": "Organization",
        ...
    }]
 }
}
```

Currently, the above script would raise `Type 'Graph' does not satisfy the constraint 'Thing'.` because of this type constraint `StructuredDataSchema extends Thing = Thing` on  `HandleStructureData` 

### Your Example Website or App

https://stackblitz.com/edit/remix-run-remix-vu3jgx?file=app/routes/index.tsx

### Steps to Reproduce the Bug or Issue

Check typing error from `structuredData`.

### Expected behavior

`StructuredDataFunction` should accept `Graph` as the second generic type.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by sergiodxa** [comment]
`StructuredDataFunction` is now marked as deprecated since V2_MetaFunction now supports sending JSON+LD and render it in script tags.
