### ISSUE TITLE
Wrong type on session.get

### ISSUE THREAD

**Issue by lauritzsh** [sergiodxa/remix-utils#192]
### Describe the bug

I'm trying to use typed sessions and I followed along [here](https://github.com/sergiodxa/remix-utils#typed-sessions), but count is not `number` as expected but rather `number | null`.

### Your Example Website or App

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgGQgQwCYFMoCCUA5gM4A0KcAxlLpjLgMIQQDWwulqt9jL7TgGVcpUsAgA7ITGiZiXJAF84AMygQQcAEQABOiGAAPALRQArpID0kiHm0BuJKEixENOg1wAVAJ5hcbBExCWlZKHlcOBV1TR0DYxNzGGAAG1JHZ3BoeAQ4AC9otQ0tbXy7TKRU3HhqVg4ogF4PPmZ6zgAKbToYcyhJbwhtAEonKpq4UmoAC1wQTDhm-IA6CAAjACtcahgO5B4ISxgALgLlyXMQNfwO4eW8VUxzVN2ARmHKJVGkcfhSUXEUhkcgUixaXgEDWCgLCINwexo7SiXzG1XgMH8gWhoWBEVBzV4Xj8ASCAJx4UiCP+ISBFIU5EmMzmCxRP1wRlc8EwpF8kmoaksO1CcFSWDwUARdAAjuZRPAlKcMDh8EQyMNEFQ6pJSH8yVIwZgAO6YYDozGkmmwvG4ZYKGDYqQdKioaWynXLWbKqCkW01LqQzgjKjfTVSHWIo5g6kw327bR1I4jJyoKxWVCoAB6AH4fgdtbVDpIYAARBgLZrR0L3MvLBNFqip9NwbPKJBAA

### Steps to Reproduce the Bug or Issue

1. Go to the URL
2. Line 24 has wrong type.
3. Line 27 has correct type.

### Expected behavior

I expected line 24 to have correct type.

### Platform

TS Playground.

**Comment by sergiodxa** [comment]
This is intended https://github.com/sergiodxa/remix-utils/blob/ea8fa3fce4cedcce492be65812d532ef5ff2265c/src/server/typed-session.ts#L38

The key may not be there and in that case it returns null.

**Comment by lauritzsh** [comment]
I see, thanks. So I assume it's because you can still do the following

```ts
session.unset('count');
const count = session.get("count");
```

You just won't be able to commit the session if I understand correctly. How come then that `session.data.count` is just `number` and not `number | null` if it can be unset, or is `data` first changed after a commit? I'm a little unsure whether it would be better to `get` or just read from `data`. Right now I just do `const count = session.get('count') ?? 1`.

If there is no way or no intention to achieve this behavior, then perhaps the documentation could be updated to the following just to avoid confusion.

```ts
let session = typedSessionStorage.getSession(request.headers.get("Cookie"));

session.get("token"); // this will be a string or undefined or null
session.get("count"); // this will be a number or null
session.get("random"); // this will make TS yell because it's not in the schema

session.has("token"); // this will be a boolean
session.has("count"); // this will be a boolean

// this will make TS yell because it's not a string, if you ignore it it will
// throw a ZodError
session.set("token", 123);
```

**Comment by sergiodxa** [comment]
You should always use `session.get("key")` and never `session.data.key`
