### ISSUE TITLE
Add support for Remix v2.0.0

### ISSUE THREAD

**Issue by jgentes** [sergiodxa/remix-utils#228]
### Describe the bug

Remix v2 has deprecated `useTransition` in favor of `useNavigation` as documented here: https://remix.run/docs/en/2.0.0/start/v2#usetransition

After upgrading to Remix v2, the following error occurs:
```
X [ERROR] No matching export in "node_modules/@remix-run/react/dist/esm/index.js" for import "useTransition"

    node_modules/remix-utils/browser/react/use-global-pending-state.js:1:9:
      1 │ import { useTransition, useFetchers } from "@remix-run/react";
```

### Your Example Website or App

https://github.com/jgentes/mixpoint

### Steps to Reproduce the Bug or Issue

Go to package.json, update all remix dependencies to "2.0.0" and run "yarn", then "yarn dev"

### Expected behavior

Probably ought to update `remix-utils` to the latest version of Remix

### Platform

Windows, edge

**Comment by zifahm** [comment]
v2 is already in the works. You can use it today by instlaling remix-utils@next

**Comment by manstfu** [comment]
> v2 is already in the works. You can use it today by instlaling remix-utils@next

> npm i remix-utils@next
> npm ERR! Found: @remix-run/react@2.0.0
> npm ERR! Could not resolve dependency:
> npm ERR! peer @remix-run/react@"^1.19.1" from remix-utils@7.0.0-pre.3

**Comment by yosonoronosoy** [comment]
I went the ape route. It works for now I guess...

```zsh
# or code instead of neovim
nvim node_modules/remix-utils/browser/react/use-global-pending-state.js
```

and change all instances of `useTransition` for `useNavigation`

```tsx
-- import { useTransition, useFetchers } from "@remix-run/react";
++ import { useNavigation, useFetchers } from "@remix-run/react";
```

**Comment by Joseamica** [comment]
```
node:internal/modules/cjs/loader:557
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/amieva/Documents/Programming/Remix-TS/av/node_modules/remix-utils/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:266:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:602:9)
    at resolveExports (node:internal/modules/cjs/loader:551:36)
    at Module._findPath (node:internal/modules/cjs/loader:620:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:27)
    at Module._load (node:internal/modules/cjs/loader:898:27)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/Users/amieva/Documents/Programming/Remix-TS/av/build/index.js:6279:205) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v19.4.0
ERROR: "dev:server" exited with 1.
```

**Comment by bushblade** [comment]
> v2 is already in the works. You can use it today by instlaling remix-utils@next

I'm seeing:

```bash
[1] ✘ [ERROR] Could not resolve "remix-utils"
[1]
[1]     app/components/RichTextRenderer.tsx:21:27:
[1]       21 │ import { ClientOnly } from 'remix-utils';
[1]          ╵                            ~~~~~~~~~~~~~
[1]
[1]   The path "." is not exported by package "remix-utils":
[1]
[1]     node_modules/remix-utils/package.json:54:13:
[1]       54 │   "exports": {
[1]          ╵              ^
[1]
[1]   You can mark the path "remix-utils" as external to exclude it from the bundle, which will remove this error.
```

**Comment by ananni13** [comment]
Why is no one reading the [v2 documentation](https://github.com/sergiodxa/remix-utils/blob/remix-v2/README.md) or even just this https://github.com/sergiodxa/remix-utils/issues/228#issuecomment-1729241106, in this same issue, from yesterday? 😅

You **CAN'T** write this anymore: 

```ts
import { ... } from "remix-utils";
``` 

You have to use the correct imports that are shown in all the new examples in the [v2 README.md](https://github.com/sergiodxa/remix-utils/blob/remix-v2/README.md).

e.g. for `ClientOnly`:

```ts
import { ClientOnly } from "remix-utils/client-only";
```

Your IDE should be more than capable of suggesting the correct imports, just delete the old ones that don't work anymore.

**Comment by jamestrenda** [comment]
> Why is no one reading the [v2 documentation](https://github.com/sergiodxa/remix-utils/blob/remix-v2/README.md) or even just this [#228 (comment)](https://github.com/sergiodxa/remix-utils/issues/228#issuecomment-1729241106), in this same issue, from yesterday? 😅
> 
> You **CAN'T** write this anymore:
> 
> ```ts
> import { ... } from "remix-utils";
> ```
> 
> You have to use the correct imports that are shown in all the new examples in the [v2 README.md](https://github.com/sergiodxa/remix-utils/blob/remix-v2/README.md), e.g. for `ClientOnly`:
> 
> ```ts
> import { ClientOnly } from "remix-utils/client-only";
> ```

That doesn't work either. VS Code is not finding those subdirectories for the import statement and when running `remix dev`, I get the following error (I replaced my real path with PATH_TO_PROJECT in case that wasn't clear):

```
Error [ERR_REQUIRE_ESM]: require() of ES Module [PATH_TO_PROJECT]/node_modules/.pnpm/remix-utils@7.0.0-pre.3_@remix-run+react@2.0.1_@remix-run+router@1.9.0_@remix-run+server-runt_yhantxcu5gjjxoe52llaxnxbj4/node_modules/remix-utils/build/react/client-only.js from [PATH_TO_PROJECT]/build/index.js not supported.

Instead change the require of client-only.js in [PATH_TO_PROJECT]/build/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/jamestrenda/code/repos/mundet/build/index.js:5281:26)
```

Any help would be greatly appreciated.

**Comment by sergiodxa** [comment]
> > Why is no one reading the [v2 documentation](https://github.com/sergiodxa/remix-utils/blob/remix-v2/README.md) or even just this [#228 (comment)](https://github.com/sergiodxa/remix-utils/issues/228#issuecomment-1729241106), in this same issue, from yesterday? 😅
> > You **CAN'T** write this anymore:
> > ```ts
> > import { ... } from "remix-utils";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You have to use the correct imports that are shown in all the new examples in the [v2 README.md](https://github.com/sergiodxa/remix-utils/blob/remix-v2/README.md), e.g. for `ClientOnly`:
> > ```ts
> > import { ClientOnly } from "remix-utils/client-only";
> > ```
> 
> That doesn't work either. VS Code is not finding those subdirectories for the import statement and when running `remix dev`, I get the following error (I replaced my real path with PATH_TO_PROJECT for brevity, in case that wasn't clear):
> 
> ```
> Error [ERR_REQUIRE_ESM]: require() of ES Module [PATH_TO_PROJECT]/node_modules/.pnpm/remix-utils@7.0.0-pre.3_@remix-run+react@2.0.1_@remix-run+router@1.9.0_@remix-run+server-runt_yhantxcu5gjjxoe52llaxnxbj4/node_modules/remix-utils/build/react/client-only.js from [PATH_TO_PROJECT]/build/index.js not supported.
> 
> Instead change the require of client-only.js in [PATH_TO_PROJECT]/build/index.js to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> ([PATH_TO_PROJECT]/build/index.js:5281:26)
> ```
> 
> Any help would be greatly appreciated.

This error is because Remix Utils v7 will ship ESM-only code, and it seems you Remix app is generating CJS code as the build output for the server, so you can't `require()` ESM modules.

You need to add `remix-utils` to `serverDependenciesToBundle` in your remix.config file.

**Comment by mufftee** [comment]
@sergiodxa and how can i use it then? do i still use `import { ClientOnly } from "remix-utils/client-only";` etc?

i stuck a little bit here.

**Comment by bushblade** [comment]
> Why is no one reading the [v2 documentation](https://github.com/sergiodxa/remix-utils/blob/remix-v2/README.md) or even just this [#228 (comment)](https://github.com/sergiodxa/remix-utils/issues/228#issuecomment-1729241106), in this same issue, from yesterday? 😅
> 
> You **CAN'T** write this anymore:
> 
> ```ts
> import { ... } from "remix-utils";
> ```
> 
> You have to use the correct imports that are shown in all the new examples in the [v2 README.md](https://github.com/sergiodxa/remix-utils/blob/remix-v2/README.md), e.g. for `ClientOnly`:
> 
> ```ts
> import { ClientOnly } from "remix-utils/client-only";
> ```
> 
> Your IDE should be more than capable of suggesting the correct imports, just delete the old ones that don't work anymore.

Probably because some people are just following guides from other docs or articles that have not been updated to V2 then finding an issue and coming here.

**Comment by micisse** [comment]
@mufftee and other people who have the same problem. You must use **regex**, not **string** like this:

```js
// remix.config.js
...
  serverDependenciesToBundle: [
    /remix-utils/ // not "remix-utils"
  ],
...

// in your component
import { ClientOnly } from "remix-utils/client-only";
```

**Comment by mufftee** [comment]
> @mufftee and other people who have the same problem. You must use **regex**, not **string** like this:
> 
> ```js
> // remix.config.js
> ...
>   serverDependenciesToBundle: [
>     /remix-utils/ // not "remix-utils"
>   ],
> ...
> 
> // in your file component
> import { ClientOnly } from "remix-utils/client-only";
> ```

Works like a charm!1

**Comment by KrisBraun** [comment]
In case this helps anyone else, I needed to update these settings in `tsconfig.json` to support the new exports:

```
{
  "compilerOptions": {
    "module": "ES2022",
    "moduleResolution": "Bundler",
    ...
  }
}
```

**Comment by stevensacks** [comment]
When I try to install remix-utils@next, it fails:
```
npm i -S remix-utils@next
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: project-v2@0.0.1
npm ERR! Found: @remix-run/react@2.0.1
npm ERR! node_modules/@remix-run/react
npm ERR!   @remix-run/react@"2.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @remix-run/react@"^1.19.1" from remix-utils@7.0.0-pre.3
npm ERR! node_modules/remix-utils
npm ERR!   remix-utils@"7.0.0-pre.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**Comment by Fireclunge** [comment]
> When I try to install remix-utils@next, it fails:
> 
> ```
> npm i -S remix-utils@next
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: project-v2@0.0.1
> npm ERR! Found: @remix-run/react@2.0.1
> npm ERR! node_modules/@remix-run/react
> npm ERR!   @remix-run/react@"2.0.1" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @remix-run/react@"^1.19.1" from remix-utils@7.0.0-pre.3
> npm ERR! node_modules/remix-utils
> npm ERR!   remix-utils@"7.0.0-pre.3" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> ```

I think for now you need to npm install with --legacy-peer-deps

**Comment by stevensacks** [comment]
Oops, yeah, I read that after and forgot to delete my comment.

**Comment by setvik** [comment]
Would be great if we the peer dependencies could be updated so that we didn't need the --legacy-peer-deps flag.

**Comment by cliffordfajardo** [comment]
> In case this helps anyone else, I needed to update these settings in `tsconfig.json` to support the new exports:
> 
> ```
> {
>   "compilerOptions": {
>     "module": "ES2022",
>     "moduleResolution": "Bundler",
>     ...
>   }
> }
> ```


I updated my tsconfig.json's `moduleResolution: "node"` to `moduleResolution: "Bundler".
NOTE: `Bundler` is only available for typescript version 5.0+

I was initially curious about how `Bundler` compares to the `node` value and others & found this comparison table from the typescript team:
![image](https://github.com/sergiodxa/remix-utils/assets/6743796/5c61cfc6-8759-46e6-a9c8-72608c79684e)


## References
- https://github.com/microsoft/TypeScript/pull/51669
- https://dev.to/ayc0/typescript-50-new-mode-bundler-esm-1jic

**Comment by DonKoko** [comment]
@cliffordfajardo indeed thats the correct tsconfig and it also worked for me, but the dependencies are still not updated and its still required to run `npm i --legacy-peer-deps` which doesn't work for us in production. Have you found a solution for that?

**Comment by zifahm** [comment]
@DonKoko [this](https://discord.com/channels/770287896669978684/1156602871136145509/1156863568344530994) was one of the suggested workarounds, have'nt tried it yet

**Comment by DonKoko** [comment]
thanks @zifahm . I was even the one who created the discussion in discord. Idk how i missed that comment. 
Solution is to add overrides to package.json
```json
  "overrides": {
    "remix-utils": {
      "@remix-run/react": "^2.0.1",
      "@remix-run/server-runtime": "^2.0.1"
    }
  },
  ```

**Comment by p-christ** [comment]
How can i do this with the new version?

```
import * as RemixUtils from 'remix-utils';
RemixUtils.eventStream(...) 

```

**Comment by sergiodxa** [comment]
You can't anymore, and you should have never done this because it would cause all utils to be bundled.

**Comment by p-christ** [comment]
oh so in the old code, this:

``` import { eventStream } from 'remix-utils' ```

leads to less being bundled than this:

``` import * as RemixUtils from 'remix-utils' ```

?  I would have thought they lead to the same amount being bundled, is this a remix specific difference?

**Comment by sergiodxa** [comment]
That's how bundlers work, by doing `* as RemixUtils` you're bringing all that the package comes with as a single object, instead of importing exactly what you need.

In the next version of Remix Utils (a new pre-release has been published btw which uses Remix v2 as dependency) each util will have a unique import path like `remix-utils/sse/server` for `eventStream` or `remix-utils/sse/react` for `useEventSource`.

**Comment by jozefmery** [comment]
Why were some of the utilities removed in the latest version ? Namely `badRequest` is something that appears to be missing,. maybe others too. Has it perhaps been replaced with something from Remix V2 itself ?

**Comment by sergiodxa** [comment]
> Why were some of the utilities removed in the latest version ? Namely `badRequest` is something that appears to be missing, maybe others too. Has it perhaps been replaced with something from Remix V2 itself ?

Most of those response utils where just wrappers of `json`, it's simpler to just use `json` instead of maintaining a wrapper.

Response helpers that add extra features or don't wrap `json` were left in the package. Examples include `redirectBack`, `jsonHash`, `namedAction`, `notModified` (because it has the limit of not receiving body or headers) and any non JSON response helper so you don't need to care about the specific content-type of the response.

**Comment by sergiodxa** [comment]
Also v7.0.1 with Remix v2 support is out as stable release https://github.com/sergiodxa/remix-utils/releases/tag/v7.0.1.

Closing this since it's released now, for any specific problem please open a new issue to treat them individually.

**Comment by saashqdev** [comment]
So, what do we do with **badRequest** and **forbidden** from V6?

**Comment by sergiodxa** [comment]
@saashqdev You can always copy them to your own codebase (they are [here](https://github.com/sergiodxa/remix-utils/blob/6d3012ffdc8ed62f7c85cd24721efe3792580357/src/server/responses.ts#L47) and [here](https://github.com/sergiodxa/remix-utils/blob/6d3012ffdc8ed62f7c85cd24721efe3792580357/src/server/responses.ts#L77)), or do `json(data, 400)` and `json(data, 403)`, they didn't do more than that

**Comment by saashqdev** [comment]
Ah, cool. Thanks a lot.

**Comment by justinmetros** [comment]
> Response helpers that add extra features or don't wrap `json` were left in the package. Examples include `redirectBack`, `jsonHash`, `namedAction`, `notModified` (because it has the limit of not receiving body or headers) and any non JSON response helper so you don't need to care about the specific content-type of the response.

Love this new version, thanks for everything with this 🙏

May I recommend adding the dropped response utils to changelog or the [Upgrade notes](https://github.com/sergiodxa/remix-utils#upgrade-from-remix-utils-v6)? Used those all over an app and thought I was taking crazy pills until I dug down into the packages. 

Simple enough to replace but may make upgrade easier for some.

**Comment by benjamindulau** [comment]
Installed v7.3.0 today and IntelliJ is complaining.
v2.3.0 of Remix.
ESM only project.

Switching to  `moduleResolution: "Bundler"` makes things worse for a lot of other imports.

![Capture d’écran 2023-11-29 à 18 18 42](https://github.com/sergiodxa/remix-utils/assets/430689/9ff86a60-7390-40eb-866e-b5ad383b2041)

**Comment by cjoecker** [comment]
@benjamindulau did you restart your Typescript server after the installation? In the bottom right corner, you can see it
![CleanShot 2023-11-30 at 08 36 26@2x](https://github.com/sergiodxa/remix-utils/assets/46030630/9b0e2edc-02fc-47e3-95c8-42878340c8ca)

**Comment by benjamindulau** [comment]
@cjoecker Yep! I restarted the entire IDE, cleared cache, restarted Typescript, everything (well I hope not everything since I didn't do what works :p)

**Comment by nicolasrenon** [comment]
Using VS Code, remix 2.3.1 and remix-utils 7.3.0 with Indie Stack, and I'm getting `Cannot find module [...] or its corresponding type declarations` on all remix-utils imports. Restarted VS Code did not solve the problem.
Any idea?

**Comment by sergiodxa** [comment]
@nicolasrenon Ensure you have TS v5, that your tsconfig.json has moduleResolution set to `bundler`, and if you're using CJS add remix-utils packages to serverDependenciesToBundle.

**Comment by sergiodxa** [comment]
If you can't switch moduleResolution to bundler then you can't upgrade to Remix Utils v7.

**Comment by manzaloros** [comment]
I'm also having this issue. Switching module resolution to "Bundler" will solve it, [but that causes problems in other places.](https://github.com/grpc/grpc-node/issues/2617).

**Comment by sergiodxa** [comment]
Note that `"moduleResolution": "Bundler"` in new Remix apps, and it's recommended by TS when working with a bundler.
