### ISSUE TITLE
v7.0.0 released accidentally?

### ISSUE THREAD

**Issue by frontendphil** [sergiodxa/remix-utils#233]
### Describe the bug

[renovate](https://github.com/renovatebot/renovate) opened up an MR to our repo with an update from `v7.0.0-pre3` to `v7.0.0`. Some checks are failing, so I went here to find the release notes. However, there are none. So, I'm wondering whether this release happened accidentally.

### Your Example Website or App

https://github.com/sergiodxa/remix-utils/releases

### Steps to Reproduce the Bug or Issue

I guess `npm i remix-utils` should give you `7.0.0` now instead of `6.6.0`

### Expected behavior

I should know which release the latest one is, that I can use :) 

### Platform

Doesn't really apply here, I think.

**Comment by gut4** [comment]
@sergiodxa Are there any blockers to release 7.0.0?

**Comment by sergiodxa** [comment]
When trying v7 prerelease I forgot to add `-pre.1` the first time and that published 7.0.0 as the `next` tag in npm.

Future latest version will be v7.0.1
