### ISSUE TITLE
remix-utils: missing type declarations (regression)

### ISSUE THREAD

**Issue by rolanday** [sergiodxa/remix-utils#249]
### Describe the bug

Latest version of remix-util is broke for me (cannot import from). A clean remix-install results in following when attempting to import:

```
app/routes/_index.tsx:1:36 - error TS2307: Cannot find module 'remix-utils' or its corresponding type declarations.

1 import { getClientIPAddress } from "remix-utils";
                                     ~~~~~~~~~~~~~


Found 1 error in app/routes/_index.tsx:1
```

Repro avail here: https://github.com/rolanday/repro-remix-util

Same result using bun and npm package managers

### Your Example Website or App

 https://github.com/rolanday/repro-remix-util

### Steps to Reproduce the Bug or Issue

1. Create new remix project (typescript)
2. `npm i remix-utils`
3. Try to import `remix-utils`
4. Note cannot find module error

### Expected behavior

To be able to import from `remix-utils`

### Platform

- OS: macOS (Sonoma v14.0)
- Browser: N/A

**Comment by sergiodxa** [comment]
This is mentioned on the [Upgrade from Remix Utils v6](https://github.com/sergiodxa/remix-utils#upgrade-from-remix-utils-v6) section of the README, specifically on the [Updated Import Paths](https://github.com/sergiodxa/remix-utils#updated-import-paths) section

**Comment by rolanday** [comment]
Thank you. My bad for not checking most obvious place (readme) for solution.

**Comment by brandonpittman** [comment]
<img width="899" alt="Screenshot 2023-10-10 at 0 04 16 PM" src="https://github.com/sergiodxa/remix-utils/assets/967145/f5e8e690-c9c4-45fd-8cb1-58073c74b1cf">

@sergiodxa 

I updated my import paths and I'm still getting the error. (The JS works though.)

**Comment by sergiodxa** [comment]
@brandonpittman did you added `"moduleResolution": "Bundler"` to `tsconfig.json`?

**Comment by brandonpittman** [comment]
<img width="851" alt="Screenshot 2023-10-11 at 10 28 48 AM" src="https://github.com/sergiodxa/remix-utils/assets/967145/6276b418-69dc-4538-89e6-4f5acad979e0">

@sergiodxa 

Yes, and I'm on the latest TypeScript, but tsserver doesn't like that value. I haven't upgraded to Remix v2 yet—not sure if that matters.

**Comment by sergiodxa** [comment]
If TS doesn't allow moduleResolution to be Bundler then you're not on TS v5.

And latest Remix Utils version needs Remix v2, if you're still in v1 it's better to stick with Remix Utils v6.

**Comment by brandonpittman** [comment]
@sergiodxa Sorry. It wound up being a problem with my editor extension for tsserver being too older to work with TSv5 and the `bundler` setting. 🙇🏻
