### ISSUE TITLE
client-only: require() is not supported

### ISSUE THREAD

**Issue by wdj82** [sergiodxa/remix-utils#252]
### Describe the bug

Trying to get remix-utils client-only working in a cjs project and getting the following error:

![image](https://github.com/sergiodxa/remix-utils/assets/37749088/5cf9a13d-6d3e-4b60-9c20-1a224107a197)

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

Create a new remix project.
Add remix-utils.
Convert to cjs - `serverModuleFormat: "cjs"` -  and remove `"type": "module"` from the package.json
Create a new route with the ClientOnly tag: `return <ClientOnly>{() => <div>Client only</div>}</ClientOnly>;`

### Expected behavior

No error

### Platform

- OS: Windows, Linux
- Browser: Chrome
- Version: 7.0.2

**Comment by sergiodxa** [comment]
Latest version is ESM only, check the README about how to use it in CJS apps.

https://github.com/sergiodxa/remix-utils#usage-with-cjs
