### ISSUE TITLE
useLocales and getClientLocales not exported from package.json

### ISSUE THREAD

**Issue by chessydk** [sergiodxa/remix-utils#253]
### Describe the bug

Like title says, these are not exported, most other utils are.

The imports in the documentation (https://github.com/sergiodxa/remix-utils#uselocales) also erroneously points to a folder that does not exist (remix-utils/locales)

Thx. for the nice utils btw and keep up the good work!

### Your Example Website or App

..

### Steps to Reproduce the Bug or Issue

Just by looking at package.json / docs.

### Expected behavior

I guess, all utils should be exported, when some are. And docs. should be correct.

### Platform

- OS: Windows
- Browser: Chrome

**Comment by bbonamin** [comment]
Are you bundling your app using commonjs? Did you upgrade from Remix v1? https://github.com/sergiodxa/remix-utils#usage-with-cjs

There are a few extra steps if so. I'm currently using this helper and I had to do this:

In `remix.config.js`, 
```typescript
// ....
  serverDependenciesToBundle: [
    ...
    "remix-utils/locales",
  ],
};

**Comment by bbonamin** [comment]
I did have to remove the `"module"` key from `tsconfig.json`.

Also my imports in `remix.config.js` ended like this ( I don't need the react side of locales for now, nor I needed to add `remix-utils`):
```
serverDependenciesToBundle: [
  // ...
  "remix-utils/locales/server"
],

**Comment by chessydk** [comment]
@bbonamin That helped! thx.

Although I do not understand why the "locales" path is understood by bundler when there is no such physical path below remix-util. 

I think it would be useful to update documentation on the specific modules to put into "serverDependenciesToBundle".

**Comment by buildtheui** [comment]
@chessydk documentation was updated and now you can simply add `/^remix-utils.*/,` instead of adding every separate util path

**Comment by dev-xo** [comment]
> Are you bundling your app using commonjs? Did you upgrade from Remix v1? https://github.com/sergiodxa/remix-utils#usage-with-cjs
> 
> There are a few extra steps if so. I'm currently using this helper and I had to do this:
> 
> In `remix.config.js`,
> 
> ```ts
> // ....
>   serverDependenciesToBundle: [
>     ...
>     "remix-utils/locales",
>   ],
> };
> ```

This made it for me, thank you!

**Comment by dev-xo** [comment]
@bbonamin 

> Are you bundling your app using commonjs? Did you upgrade from Remix v1? https://github.com/sergiodxa/remix-utils#usage-with-cjs
> 
> There are a few extra steps if so. I'm currently using this helper and I had to do this:
> 
> In `remix.config.js`,
> 
> ```ts
> // ....
>   serverDependenciesToBundle: [
>     ...
>     "remix-utils/locales",
>   ],
> };
> ```

This made it for me, thank you!
