### ISSUE TITLE
Failed to resolve entry for package "remix-utils".

### ISSUE THREAD

**Issue by cjoecker** [sergiodxa/remix-utils#278]
### Describe the bug

When I mock `remix-ultils` with `vitest` as `vi.mock("remix-utils")`, I get the error 
`Error: Failed to resolve entry for package "remix-utils". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier`

### Your Example Website or App

[codesandbox.io/p/devbox/validated-form-error-forked-kd6m28?file=%2Fsrc%2FApp.test.tsx%3A10%2C1](https://codesandbox.io/p/devbox/validated-form-error-forked-kd6m28?file=%2Fsrc%2FApp.test.tsx%3A10%2C1)

### Steps to Reproduce the Bug or Issue

Open codesandbox and see the terminal errors while running tests.

### Expected behavior

There is no error on mocking `remix-utils`

### Platform

- `remix-utils` v. 7.1.0

**Comment by sergiodxa** [comment]
There’s nothing at remix-utils, each util is a different module. You can see how to import each util individually in the README.

**Comment by kevinreber** [comment]
Recently upgraded to Remix `v2` and am having an issue where VSCode isn't picking up any of the `remix-utils` modules when using the same import path shown in the  [Honeypot README examples](https://github.com/sergiodxa/remix-utils#form-honeypot)
![CleanShot 2023-11-21 at 20 04 48](https://github.com/sergiodxa/remix-utils/assets/42260999/299aff00-b617-4e75-aa8c-a9d509685a66)

Everything works fine when using relative import paths
![CleanShot 2023-11-21 at 20 15 40](https://github.com/sergiodxa/remix-utils/assets/42260999/683910c3-2548-4c01-837d-a4acee1e9c89)

`remix.config.js`
```js
/** @type {import('@remix-run/dev').AppConfig} */
import { config } from "@netlify/remix-adapter";

export default {
  serverModuleFormat: "esm",
  ...config,
  ignoredRouteFiles: ["**/.*"],
  serverPlatform: "node",
  server:
    process.env.NETLIFY || process.env.NETLIFY_LOCAL
      ? "./server.ts"
      : undefined,
  serverBuildPath: ".netlify/functions-internal/server.js",
  postcss: false,
  tailwind: true,
  serverDependenciesToBundle: [
    "@radix-ui/themes",
    /^rc-util.*/,
  ],
};
```

`tsconfig.json`
```json
{
  "include": ["remix.env.d.ts", "**/*.ts", "**/*.tsx"],
  "compilerOptions": {
    "lib": ["DOM", "DOM.Iterable", "ES2019"],
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "target": "ES2019",
    "strict": true,
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./app/*"]
    },
    "noEmit": true
  }
}
```

`package.json`
```json
{
  "private": true,
  "sideEffects": false,
  "type": "module",
  "scripts": {
    "build": "remix build",
    "dev": "yarn run check-env-file && remix dev --manual",
    "start": "netlify dev",
    "typecheck": "tsc",
    "check-env-file": "node ./scripts/check-env-file.mjs",
    "postinstall": "prisma generate",
    "stripe:listen": "stripe listen --forward-to localhost:3000/webhook",
    "format": "prettier --write .",
    "lint": "eslint --cache --cache-location ./node_modules/.cache/eslint ."
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.363.0",
    "@conform-to/react": "^0.9.1",
    "@conform-to/zod": "^0.9.1",
    "@heroicons/react": "^2.0.18",
    "@netlify/functions": "^2.3.0",
    "@netlify/remix-adapter": "^2.2.0",
    "@prisma/client": "^4.13.0",
    "@radix-ui/colors": "^3.0.0",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-select": "^2.0.0",
    "@radix-ui/react-switch": "^1.0.3",
    "@radix-ui/themes": "^2.0.1",
    "@remix-run/css-bundle": "^2.2.0",
    "@remix-run/express": "^2.2.0",
    "@remix-run/node": "2.2.0",
    "@remix-run/react": "2.2.0",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.0.0",
    "cross-env": "^7.0.3",
    "dotenv": "^16.0.3",
    "isbot": "^3.6.8",
    "openai": "^3.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "remix-auth": "^3.6.0",
    "remix-auth-socials": "^2.0.5",
    "remix-utils": "^7.1.0",
    "stripe": "^12.3.0",
    "tailwind-merge": "^2.0.0",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@remix-run/dev": "2.2.0",
    "@remix-run/eslint-config": "2.2.0",
    "@remix-run/serve": "2.2.0",
    "@types/eslint": "^8.44.3",
    "@types/react": "^18.0.35",
    "@types/react-dom": "^18.0.11",
    "eslint": "^8.38.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^9.0.0",
    "prettier": "^3.0.3",
    "prisma": "^4.13.0",
    "tailwindcss": "^3.3.3",
    "typescript": "^4.9.5",
    "zx": "7.0.8"
  },
  "engines": {
    "node": "20.5.0"
  }
}

```

**Comment by kevinreber** [comment]
By some miracle my issue just disappeared, didn't do anything special 😅 
Feel free to ignore my comments 🙏  ⬆️ ⬆️

**Comment by vedovelli** [comment]
I am having issues while upgrading Remix to the latest version.

My `remix-utils` is the latest:
![CleanShot 2023-11-28 at 14 38 47](https://github.com/sergiodxa/remix-utils/assets/151001/edc27088-d9f4-419e-8a17-dc8e6b105f68)

But I can't build my project:
![CleanShot 2023-11-28 at 14 38 00](https://github.com/sergiodxa/remix-utils/assets/151001/d1412e23-2d23-405b-97f2-021d161a1398)

VSCode won't import from the proper place as well:
![CleanShot 2023-11-28 at 14 49 02](https://github.com/sergiodxa/remix-utils/assets/151001/1e0907ad-94bf-489d-a4e1-a027fb6e7b51)

Can I get some help with the issue?

**Comment by Diyouf** [comment]
[plugin:vite:import-analysis] Failed to resolve entry for package "remix-utils". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "remix-utils" package


dose any have the issue , I already installed the package but it is not working properly

**Comment by sergiodxa** [comment]
@Diyouf you can't import directly from `remix-utils` you need to use `remix-utils/something`, check the README to see the different things exported by the package.

**Comment by Diyouf** [comment]
@sergiodxa thank you for the information , have a nice day
