### ISSUE TITLE
 Cannot find module remix-utils/use-hydrated or its corresponding type declarations.

### ISSUE THREAD

**Issue by justinhandley** [sergiodxa/remix-utils#297]
### Describe the bug

I'm getting this feedback in Intellij - although everything works fine, I'm just wondering why I'm getting this feedback.  Tried installing @types/remix-utils but it doesn't exists - and I think not necessary.

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

Install the latest version
import { useHydrated } from 'remix-utils/use-hydrated'

### Expected behavior

No lint error

### Screenshots or Videos

<img width="1717" alt="Screenshot 2024-01-08 at 1 27 18 PM" src="https://github.com/sergiodxa/remix-utils/assets/9010117/f9f87558-2cac-416f-b3b9-60419033c04e">

### Platform

version 7.5.0

**Comment by sergiodxa** [comment]
Ensure your tsconfig.json has `"moduleResolution": "Bundler"`.

Also see https://github.com/sergiodxa/remix-utils#upgrade-from-remix-utils-v6.

**Comment by justinhandley** [comment]
This did the trick - thanks!
