### ISSUE TITLE
Why is `@remix-run/server-runtime` a peer dependency when it's not used?

### ISSUE THREAD

**Issue by tom-sherman** [sergiodxa/remix-utils#34]
It shows a warning/error when using pnpm and npm with new peer deps checks.

I think it can be removed?

**Comment by sergiodxa** [comment]
It's used here https://github.com/sergiodxa/remix-utils/blob/7da3005fa8071a824c50200b3a9032f55e288b75/src/server/csrf.ts#L1 and https://github.com/sergiodxa/remix-utils/blob/7da3005fa8071a824c50200b3a9032f55e288b75/src/server/responses.ts#L1
