### ISSUE TITLE
Add getClienIPAddress helper

### ISSUE THREAD

**Issue by sergiodxa** [sergiodxa/remix-utils#48]
The helper should receive a Request or Headers object and try to get the IP address from the following headers:

1. X-Client-IP
2. X-Forwarded-For
3. CF-Connecting-IP
4. Fastly-Client-Ip
5. True-Client-Ip
6. X-Real-IP
7. X-Cluster-Client-IP
8. X-Forwarded, Forwarded-For and Forwarded

**Comment by mcansh** [comment]
Fly.io has `fly-client-ip` too 😬

**Comment by sergiodxa** [comment]
@mcansh that's too new to be on the StackOverflow answer where I got the list of headers 😅

**Comment by sergiodxa** [comment]
@mcansh done https://github.com/sergiodxa/remix-utils/pull/51, the nice thing is that adding new headers it's just adding to the list and that's all

**Comment by mcansh** [comment]
> the nice thing is that adding new headers it's just adding to the list and that's all

nice! I was going to make a PR after I finished some cli work :) - thanks!

**Comment by sergiodxa** [comment]
Released too https://github.com/sergiodxa/remix-utils/releases/tag/v2.7.0
