### ISSUE TITLE
Invalid Hook Call

### ISSUE THREAD

**Issue by ConnorVO** [sergiodxa/remix-utils#67]
### Describe the bug

I'm getting an `Invalid Hook Call` error when using `<ClientOnly>`.

If I comment out the ClientOnly tags, it works fine. When I put ClientOnly in, I get the error below

> Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
>     at resolveDispatcher (/Users/connorvanooyen/Desktop/node_modules/react/cjs/react.development.js:1476:13)
>     at Object.useState (/Users/connorvanooyen/Desktop/node_modules/react/cjs/react.development.js:1507:20)
>     at Object.useHydrated (/Users/connorvanooyen/Desktop/node_modules/remix-utils/build/react/use-hydrated.js:24:43)
>     at ClientOnly (/Users/connorvanooyen/Desktop/node_modules/remix-utils/build/react/client-only.js:22:27)
>     at processChild (/Users/connorvanooyen/Desktop/Yellowbrick/yb-stats-dash/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
>     at resolve (/Users/connorvanooyen/Desktop/Yellowbrick/yb-stats-dash/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
>     at ReactDOMServerRenderer.render (/Users/connorvanooyen/Desktop/Yellowbrick/yb-stats-dash/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
>     at ReactDOMServerRenderer.read (/Users/connorvanooyen/Desktop/Yellowbrick/yb-stats-dash/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
>     at renderToString (/Users/connorvanooyen/Desktop/Yellowbrick/yb-stats-dash/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
>     at handleRequest (/Users/connorvanooyen/Desktop/Yellowbrick/yb-stats-dash/api/index.js:48:49)

### Your Example Website or App

localhost

### Steps to Reproduce the Bug or Issue

1. Create Remix Run app
2. In Index, import and add ClientOnly with any test code in it
3. Run `npm run dev`
4. Error

### Expected behavior

Should not have error

### Platform

- OS: macOS
- Browser: Chrome

**Comment by sergiodxa** [comment]
Are you using React v18?

**Comment by ConnorVO** [comment]
No. 
<img width="175" alt="image" src="https://user-images.githubusercontent.com/20797748/162960290-2d2a3ace-8185-463d-8596-f5d1bb12d39a.png">

**Comment by sergiodxa** [comment]
Please try to create a reproduction repository so I could debug it
