### ISSUE TITLE
Error when using useDataRefresh

### ISSUE THREAD

**Issue by aiji42** [sergiodxa/remix-utils#68]
### Describe the bug

Refresh failed with an error when using `useDataRefresh`.
![スクリーンショット 2022-04-13 午前0 53 04](https://user-images.githubusercontent.com/6711766/163004226-037d9b6c-b507-4597-addc-501b697d5f54.png)

> The way this works is by sending a fetcher.submit to /dev/null to trigger all loaders to run..

Since the README states this, I solved the problem by creating `app/routes/dev/null.ts` and exporting it with an empty action defined.  
Is this the right way to do it? Or is it originally expected to function without this route file present?
If it is necessary to create this file, it should be clearly stated in the README.

### Your Example Website or App

https://github.com/aiji42/remix-utils-sample

### Steps to Reproduce the Bug or Issue

Use `useDataRefresh` without `app/routes/dev/null.ts`.

### Expected behavior

Refresh by `useDataRefresh` without `app/routes/dev/null.ts`. Alternatively, the README specifies that `app/routes/dev/null.ts` needs to be created.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 
    - remix-utils: 3.0.0
    - remix: 1.3.5

**Comment by sergiodxa** [comment]
Behavior is correct, the docs are wrong, I forgot to mention you need to create that URL, would you like to send a PR mentioning it?

**Comment by aiji42** [comment]
@sergiodxa Thanks. Yes, I would love to. I'll get to work on it.
